version: "{build}"

# Build only on tags
skip_non_tags: true

environment:
  matrix:
    - ARCH: x64
    - ARCH: x86

matrix:
  fast_finish: true

# Shallow clone cannot be used when using git-submodule
shallow_clone: false

build:
  verbosity: minimal

before_build:
  - '"C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /%ARCH% /release'
  - '"%APPVEYOR_BUILD_FOLDER%\appveyor.bat" install'

build_script:
  - '"%APPVEYOR_BUILD_FOLDER%\appveyor.bat" build'

after_build:
  - '"%APPVEYOR_BUILD_FOLDER%\appveyor.bat" package'

test_script:
  - '"%APPVEYOR_BUILD_FOLDER%\appveyor.bat" test'

artifacts:
  - path: gvim_*_x86.zip
    name: gVim_x86
  - path: gvim_*_x64.zip
    name: gVim_x64
  - path: gvim_*_x86.exe
    name: gVim_x86_installer
  - path: gvim_*_x64.exe
    name: gVim_x64_installer

deploy:
  - provider: GitHub
    description: |
      Nightly Vim Windows build snapshots

      Download and execute the most recent gvim_7.X.X_x86.exe file to install Vim.

      Vim will work without the following. However, if the specified version for a language is also installed, Vim can use it to provide extra features.

      * [ActivePerl](http://www.activestate.com/activeperl/downloads) 5.22
      * [ActiveTcl](http://www.activestate.com/activetcl/downloads) 8.6
      * [LuaBinaries](http://luabinaries.sourceforge.net/download.html) 5.3
      * [Python](https://www.python.org/downloads/) 2.7
      * [Python](https://www.python.org/downloads/) 3.4
      * [Racket](https://download.racket-lang.org/) 6.3
      * [RubyInstaller](http://rubyinstaller.org/downloads/) 2.2

      Make sure that you install x86 (32-bit) versions when you use gvim_7.X.X_x86.exe.
    auth_token:
      # Update the following key, once this is merged to Vim main repository:
      secure: ZfZRBCokF4rGIlyS0Nmgcn3g30vhz48ZKvIsF4ZGTv5HYVVPvldOtNQt3ZhtVUEl
    artifact: /gVim/
    draft: false
    prerelease: false
    on:
      appveyor_repo_tag: true

# vim: ts=2 sw=2 et
